-- Durable analytics storage for serverless deployments.
-- Vercel's /tmp filesystem is ephemeral and cannot be used for counters.

CREATE TABLE IF NOT EXISTS public.analytics_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id TEXT NOT NULL UNIQUE,
  event_type TEXT NOT NULL CHECK (
    event_type IN ('page_view', 'product_click', 'add_to_cart')
  ),
  visitor_id TEXT NOT NULL,
  session_id TEXT NOT NULL,
  path TEXT,
  referrer TEXT,
  product_id TEXT,
  product_name TEXT,
  category TEXT,
  image TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS analytics_events_created_at_idx
  ON public.analytics_events (created_at DESC);

CREATE INDEX IF NOT EXISTS analytics_events_type_created_at_idx
  ON public.analytics_events (event_type, created_at DESC);

CREATE INDEX IF NOT EXISTS analytics_events_session_idx
  ON public.analytics_events (session_id);

CREATE INDEX IF NOT EXISTS analytics_events_visitor_idx
  ON public.analytics_events (visitor_id);

ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;

-- Browser clients never access this table directly. Tracking and reporting
-- go through the Express API, which uses the Supabase service role.
REVOKE ALL ON public.analytics_events FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.get_analytics_overview(
  p_since TIMESTAMPTZ DEFAULT NULL
)
RETURNS JSONB
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  WITH filtered AS (
    SELECT *
    FROM public.analytics_events
    WHERE p_since IS NULL OR created_at >= p_since
  ),
  summary AS (
    SELECT
      COUNT(*) FILTER (WHERE event_type = 'page_view')::INTEGER AS page_views,
      COUNT(DISTINCT visitor_id)
        FILTER (WHERE event_type = 'page_view')::INTEGER AS unique_visitors,
      COUNT(DISTINCT session_id)
        FILTER (WHERE event_type = 'page_view')::INTEGER AS sessions
    FROM filtered
  ),
  product_clicks AS (
    SELECT COALESCE(
      JSONB_AGG(
        JSONB_BUILD_OBJECT(
          'id', id,
          'count', event_count,
          'name', name,
          'category', category,
          'image', image
        )
        ORDER BY event_count DESC
      ),
      '[]'::JSONB
    ) AS data
    FROM (
      SELECT
        product_id AS id,
        COUNT(*)::INTEGER AS event_count,
        MAX(COALESCE(product_name, product_id)) AS name,
        MAX(COALESCE(category, 'Unknown')) AS category,
        MAX(COALESCE(image, '')) AS image
      FROM filtered
      WHERE event_type = 'product_click' AND product_id IS NOT NULL
      GROUP BY product_id
    ) grouped_clicks
  ),
  cart_additions AS (
    SELECT COALESCE(
      JSONB_AGG(
        JSONB_BUILD_OBJECT(
          'id', id,
          'count', event_count,
          'name', name,
          'category', category,
          'image', image
        )
        ORDER BY event_count DESC
      ),
      '[]'::JSONB
    ) AS data
    FROM (
      SELECT
        product_id AS id,
        COUNT(*)::INTEGER AS event_count,
        MAX(COALESCE(product_name, product_id)) AS name,
        MAX(COALESCE(category, 'Unknown')) AS category,
        MAX(COALESCE(image, '')) AS image
      FROM filtered
      WHERE event_type = 'add_to_cart' AND product_id IS NOT NULL
      GROUP BY product_id
    ) grouped_additions
  )
  SELECT JSONB_BUILD_OBJECT(
    'pageViews', summary.page_views,
    'uniqueVisitors', summary.unique_visitors,
    'sessions', summary.sessions,
    'productClicks', product_clicks.data,
    'cartAdditions', cart_additions.data
  )
  FROM summary, product_clicks, cart_additions;
$$;

REVOKE ALL ON FUNCTION public.get_analytics_overview(TIMESTAMPTZ)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_analytics_overview(TIMESTAMPTZ)
  TO service_role;

NOTIFY pgrst, 'reload schema';
